/* DO NOT EDIT THIS FILE - it is machine generated */
#include "../../../../../../../../Software/AndroidStudio/sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_app808_HelloNdk */

#ifndef _Included_com_app808_HelloNdk
#define _Included_com_app808_HelloNdk
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_demos_yxn_lifecircle_ndktest_HelloNdk
 * Method:    getString
 * Signature: (DD)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_app808_HelloNdk_getString
  (JNIEnv *, jclass, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
