/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "../../../../../../../../Software/AndroidStudio/sdk/ndk-bundle/sysroot/usr/include/jni.h"
/* Header for class com_app808_HelloNdk */

#ifndef _Included_com_app808_HelloNdk
#define _Included_com_app808_HelloNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_app808_HelloNdk
 * Method:    cInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_app808_HelloNdk_cInit
  (JNIEnv *, jclass, jstring, jstring, jint, jint, jstring);

/*
 * Class:     com_app808_HelloNdk
 * Method:    cLogin
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_app808_HelloNdk_cLogin
  (JNIEnv *, jclass);

/*
 * Class:     com_app808_HelloNdk
 * Method:    cLoginLen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_app808_HelloNdk_cLoginLen
  (JNIEnv *, jclass);

/*
 * Class:     com_app808_HelloNdk
 * Method:    cParseCmd
 * Signature: (I[B)I
 */
JNIEXPORT jint JNICALL Java_com_app808_HelloNdk_cParseCmd
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_app808_HelloNdk
 * Method:    cGetPositon
 * Signature: (DDDDDLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_app808_HelloNdk_cGetPositon
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

/*
 * Class:     com_app808_HelloNdk
 * Method:    cGetPositonLen
 * Signature: (DDDDDLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_app808_HelloNdk_cGetPositonLen
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble, jstring);

#ifdef __cplusplus
}
#endif
#endif
